# Import Numpy

In [2]:
import numpy as np

# Creating Matrix: 2-D Array

In [ ]:
# Create the following rank 2 array with shape (3, 2)

data = np.array([[1,2], [3,4], [5,6]])
print(data)

In [ ]:
ones=np.ones((3,2))
print(ones)

In [ ]:
zeros=np.zeros((3,2))
print(zeros)

In [ ]:
random=np.random.random((3,2))
print(zeros)

# Matrix Arithmetic Operations

In [ ]:
addition = data + ones 
print(addition)

In [ ]:
multiplication= data*zeros
print (multiplication)

# Matrix Indexing and Slicing

In [ ]:
index1=data[0,1]
print(index1)

In [ ]:
slice1=data[0:2]
print(slice1)

In [ ]:
slice2=data[0:2,0]
print(slice2)

# Matrix Aggregation

In [ ]:
print(data.max())
print(data.min())
print(data.sum())

# Transposing

In [ ]:
dataT=data.T
print(dataT)

# Reshaping

In [ ]:
data_vertical=data.reshape(6,1)
print(data_vertica)

In [ ]:
data_horizontal=data.reshape(1,6)
print(data_horizontal)

In [ ]:
data_landscape=data.reshape(2,3)
print(data_landscape)

# Big Matrix

In [11]:
la= np.arange(36) #creates array of numbers from 0 to 36

In [12]:
print(la)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [13]:
bm=la.reshape(6,6)

In [14]:
print(bm)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# Exercise